### ISSUE TITLE
Typed Go_Router?

### ISSUE THREAD

**Issue by JohnGalt1717** [JonasWanke/swipeable_page_route#48]
I can't figure out from the documentation how to update this typed Go_Router route:

@immutable
class DiscoverRoute extends GoRouteData {
  @override
  Widget build(BuildContext context, GoRouterState state) {
    return DiscoverPage();
  }
}

Using SwipablePageRoute doesn't return a widget, so I'm trying to figure out what I need to do here. It would be really helpful if the documentation covered this case.

Thanks!

**Comment by Tuandiep98** [comment]
@JohnGalt1717 Just create a custom page extends SwipeablePage and throws it on GoRouter page builder like this `class SwipeablePageCustom extends SwipeablePage<void> {
  SwipeablePageCustom({
    required LocalKey key,
    required Widget child,
  }) : super(
          key: key,
          canOnlySwipeFromEdge: true,
          transitionDuration: const Duration(milliseconds: 350),
          reverseTransitionDuration: const Duration(milliseconds: 350),
          builder: (BuildContext context) => MaxWidthBox(
            maxWidth: 1200,
            background: Container(color: Theme.of(context).colorScheme.surface),
            child: child,
          ),
        );
}
`
` GoRoute(
                        name: childrendashboard,
                        path: 'dashboard',
                        pageBuilder:
                            (BuildContext context, GoRouterState state) {
                          return SwipeablePageCustom(
                            key: UniqueKey(),
                            child: DashboardScreen(
                                room: state.extra as RoomModel?),
                          );
                        },`

**Comment by Tuandiep98** [comment]
@JohnGalt1717 Just create a custom page extends SwipeablePage and throws it on GoRouter page builder like this

```dart
class SwipeablePageCustom extends SwipeablePage<void> {
  SwipeablePageCustom({
    required LocalKey key,
    required Widget child,
  }) : super(
          key: key,
          canOnlySwipeFromEdge: true,
          transitionDuration: const Duration(milliseconds: 350),
          reverseTransitionDuration: const Duration(milliseconds: 350),
          builder: (BuildContext context) => MaxWidthBox(
            maxWidth: 1200,
            background: Container(color: Theme.of(context).colorScheme.surface),
            child: child,
          ),
        );
}

GoRoute(
                        name: childrendashboard,
                        path: 'dashboard',
                        pageBuilder:
                            (BuildContext context, GoRouterState state) {
                          return SwipeablePageCustom(
                            key: UniqueKey(),
                            child: DashboardScreen(
                                room: state.extra as RoomModel?),
                          );
                        },`
```

**Comment by JonasWanke** [comment]
Sorry for the delay! I added a go_router_builder version in the example: https://github.com/JonasWanke/swipeable_page_route/commit/6fca6b80f7ad59d2301e32a5c9166d2c9b24603f (based on https://pub.dev/documentation/go_router_builder/latest/#transition-override). Unfortunately, I get a failed assertion when dragging a page away (not when using the back button), which doesn't happen with the normal go_router:

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/heroes.dart': Failed assertion: line 747 pos 14: 'manifest.fromHero != newManifest.fromHero': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      _HeroFlight.divert (package:flutter/src/widgets/heroes.dart:747:14)
heroes.dart:747
#3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:1002:26)
heroes.dart:1002
#4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:926:9)
heroes.dart:926
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
binding.dart:1392
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1326:11)
binding.dart:1326
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
binding.dart:1171
#8      _invoke (dart:ui/hooks.dart:312:13)
hooks.dart:312
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#10     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════
```

I haven't been able to pinpoint where the difference lies between the two, and won't have time to debug it in more detail until at least the week after next. Feel free to give it a try, maybe you have an idea to fix the bug – I'm using go_router_builder for the first time today

**Comment by Tuandiep98** [comment]
@JonasWanke  I'm also faced that after upgrade version flutter higher than 3.16.9, looks like the new flutter makes some changes about that, you can downgrade flutter and retry, hope it helps.

**Comment by JonasWanke** [comment]
@Tuandiep98 Did you have that error with go_router_builder or even without it? Unfortunately, with Flutter's breaking change (see #52), the new version of this package only supports Flutter 3.22 and newer, so the workaround (older Flutter version) only works with older versions of this package

**Comment by Tuandiep98** [comment]
@JonasWanke I'm just using page builder like code attached above.
